// [lolps] 单局复盘的完整句子集中维护，避免在模板中拼接归因结论。
export const reviewViewText = {
  review: '单局复盘',
  victory: '胜利',
  defeat: '失败',
  versus: '对位',
  unknownOpponent: '未识别对位',
  patch: '版本',
  game: '对局',
  snapshots: '对线与团队快照',
  personalGold: '对位经济差',
  personalCs: '对位补刀差',
  teamGold: '团队经济差',
  signedHint: '正值代表本人或我方领先；缺失数据以 — 显示。',
  snapshotMissing: '该时间附近没有可用快照',
  moments: '值得回看的片段',
  momentsHint: '这些片段用于定位录像；事件先后不代表因果关系。',
  momentsEmpty: '没有识别到符合条件的关键片段。仍可查看完整时间线。',
  inspect: '查看片段',
  selected: '正在查看',
  evidence: '关联事件',
  clearMoment: '退出片段',
  personal: '本人对位',
  team: '我方团队',
  both: '同时显示',
  chart: '经济差走势',
  chartHint: '点击曲线定位快照；断线处表示数据缺失，折线不代表帧间的真实变化。',
  chartEmpty: '没有可用的经济差快照',
  gold: '金币',
  map: '地图时间线',
  mapAlt: '召唤师峡谷地图',
  snapshot: '位置快照',
  exactEvent: '选中事件',
  playbackHint: '逐帧播放服务端位置快照，不还原连续走位。事件标记使用事件记录坐标。',
  noFrames: '没有可用的位置时间线',
  previous: '上一帧',
  next: '下一帧',
  play: '播放',
  pause: '暂停',
  replay: '重播',
  lastFrame: '已到最后一帧',
  speed: '播放速度',
  slider: '选择位置快照',
  allPlayers: '双方英雄',
  ownPlayer: '仅本人',
  eventsOnly: '仅事件',
  showEvents: '显示事件',
  me: '本人',
  opponent: '对位',
  ally: '我方',
  enemy: '敌方',
  blue: '蓝方',
  red: '红方',
  dead: '该帧已死亡',
  noPosition: '该帧无位置',
  unknownLife: '存活状态未知',
  alive: '该帧存活',
  cs: '补刀',
  level: '等级',
  participants: '英雄快照',
  noFocusedPlayer: '选择地图或列表中的英雄，查看该帧数据。',
  events: '事件记录',
  related: '本人相关',
  allEvents: '全部事件',
  anyType: '全部类型',
  kills: '击杀',
  buildings: '建筑',
  monsters: '史诗野怪',
  noEvents: '当前筛选下没有事件',
  noCoordinates: '无坐标',
  system: '系统 / 未知来源',
  unknownPlayer: '未识别英雄',
  unknownObjective: '未知目标',
  unknownBuilding: '建筑',
  turret: '防御塔',
  inhibitor: '水晶',
  top: '上路',
  mid: '中路',
  bottom: '下路',
  dragon: '巨龙',
  baron: '纳什男爵',
  herald: '峡谷先锋',
  voidGrub: '虚空巢虫',
  atakhan: '厄塔汗',
  elder: '远古巨龙',
  eventWindow: (start: string, end: string) => `地图事件区间：${start}–${end}`,
  frameCount: (current: number, total: number) => `第 ${current} / ${total} 帧`,
  eventCount: (count: number) => `共 ${count} 条`,
  sampledAt: (time: string) => `实际采样 ${time}`,
  checkpoint: (minute: number) => `${minute} 分钟`,
  moreEvidence: (count: number) => `另有 ${count} 条关联事件，可在片段中查看`,
  kill: (killer: string, victim: string) => `${killer} 击杀 ${victim}`,
  objective: (actor: string, objective: string) => `${actor} 拿下 ${objective}`,
  assists: (names: string) => `助攻：${names}`,
  shutdown: (gold: number) => `终结赏金 ${gold.toLocaleString()}`,
  mapPlayerLabel: (name: string, team: string, state: string) => `${name}，${team}，${state}`,
  selectedRange: (start: string, end: string) => `正在查看 ${start}–${end} 的片段事件`
} as const
